namespace SunamoDevCode.Values;

/// <summary>
/// Visual Studio temporary files, folders and extensions wrapped with backslashes (quotes).
/// Only contains folder lists - all values from VisualStudioTempFse wrapped for command-line usage.
/// </summary>
public class VisualStudioTempFseWrapped
{
    #region 1) To delete
    /// <summary>
    /// Folders to delete in solution directory, wrapped with quotes for command-line usage.
    /// </summary>
    public static List<string> FoldersInSolutionToDelete = null!;

    /// <summary>
    /// Folders to delete in project directory, wrapped with quotes for command-line usage.
    /// </summary>
    public static List<string> FoldersInProjectToDelete = null!;

    /// <summary>
    /// Folders to delete anywhere in hierarchy, wrapped with quotes for command-line usage.
    /// </summary>
    public static List<string> FoldersAnywhereToDelete = null!;
    #endregion

    #region 2) To keep
    /// <summary>
    /// Folders to keep in solution directory, wrapped with quotes for command-line usage.
    /// </summary>
    public static List<string> FoldersInSolutionToKeep = null!;

    /// <summary>
    /// Folders to keep in project directory, wrapped with quotes for command-line usage.
    /// </summary>
    public static List<string> FoldersInProjectToKeep = null!;

    /// <summary>
    /// Folders to keep anywhere in hierarchy, wrapped with quotes for command-line usage.
    /// </summary>
    public static List<string> FoldersAnywhereToKeep = null!;
    #endregion

    #region 3) Downloaded
    /// <summary>
    /// Folders downloaded/generated by package managers, wrapped with quotes for command-line usage.
    /// </summary>
    public static List<string> FoldersInSolutionDownloaded = null!;

    /// <summary>
    /// Folders downloaded in project directory, wrapped with quotes for command-line usage.
    /// </summary>
    public static List<string> FoldersInProjectDownloaded = null!;

    /// <summary>
    /// Folders downloaded anywhere in hierarchy, wrapped with quotes for command-line usage.
    /// </summary>
    public static List<string> FoldersAnywhereDownloaded = null!;
    #endregion

    /// <summary>
    /// Web-related file extensions and folders wrapped with quotes.
    /// </summary>
    public static List<string> FilesWeb = null!;

    /// <summary>
    /// Aggregated list of all folders and files (from all categories) wrapped with quotes.
    /// Used for checking if a path should be indexed.
    /// </summary>
    public static List<string> Aggregate = null!;

    /// <summary>
    /// Determines whether the specified path should be indexed.
    /// Returns false if the path contains any pattern from the aggregate list.
    /// </summary>
    /// <param name="path">Path to check for indexing eligibility.</param>
    /// <returns>True if the path should be indexed, false otherwise.</returns>
    public static bool IsToIndexed(string path)
    {
        if (SH.ContainsAtLeastOne(path, Aggregate))
        {
            return false;
        }
        return true;
    }

    static VisualStudioTempFseWrapped()
    {
        #region 1) To delete
        FoldersInSolutionToDelete = CA.WrapWith(VisualStudioTempFse.FoldersInSolutionToDelete, "\"");
        FoldersInProjectToDelete = CA.WrapWith(VisualStudioTempFse.FoldersInProjectToDelete, "\"");
        FoldersAnywhereToDelete = CA.WrapWith(VisualStudioTempFse.FoldersAnywhereToDelete, "\"");
        #endregion

        #region 2) To keep
        FoldersInSolutionToKeep = CA.WrapWith(VisualStudioTempFse.FoldersInSolutionToKeep, "\"");
        FoldersInProjectToKeep = CA.WrapWith(VisualStudioTempFse.FoldersInProjectToKeep, "\"");
        FoldersAnywhereToKeep = CA.WrapWith(VisualStudioTempFse.FoldersAnywhereToKeep, "\"");
        #endregion

        #region 3) Downloaded
        FoldersInSolutionDownloaded = CA.WrapWith(VisualStudioTempFse.FoldersInSolutionDownloaded, "\"");
        FoldersInProjectDownloaded = CA.WrapWith(VisualStudioTempFse.FoldersInProjectDownloaded, "\"");
        FoldersAnywhereDownloaded = CA.WrapWith(VisualStudioTempFse.FoldersAnywhereDownloaded, "\"");
        #endregion

        FilesWeb = CA.WrapWith(VisualStudioTempFse.FilesWeb, "\"");
        Aggregate = CA.JoinIList(FoldersInSolutionToDelete,
FoldersInProjectToDelete,
FoldersInSolutionDownloaded,
FoldersAnywhereToDelete,
FoldersInSolutionToKeep,
FoldersInProjectToKeep,
FoldersInProjectDownloaded, FilesWeb);
    }
}